# Tutorial on the Basics of Python

<p style="font-size:16px"> Computational Physics <br> Tutor: Rawan M. Nowier <br> Original Author: Kanishk Chauhan  </p>

***

Python is amongst the simplest and most powerful programming languages used in all fields of science and engineering. Because of its ease of use and a remarkable documentation by the makers of python and people around the world, answers to most of our questions regarding the syntax, what functions to use, etc. can be found everywhere on the internet. In this tutorial, we will go over the basics of python while providing you with links to useful websites and documentation to familiarize yourself with basic python and commonly used libraries (modules).

Python by itself has a limited functionality but the packages (libraries) such as Numpy, SciPy, Pandas, and Matplotlib make it powerful and provide us with the data structures and functions which can be used to solve the problems at hand. 

Before diving into the libraries, let's familiarize ourselves with the basics of python and see what all python alone can do. [Beginners Guide](https://wiki.python.org/moin/BeginnersGuide/Programmers) has a lot of helpful tutorials that we highly recommend.

This tutorial should take us 90 minutes to finish.


## Variables and Operators

In the following, we will briefly go over some of the most common things required to do well in computational physics course. For more on the basics of programming with python, [an excellent source is available here.](https://learnxinyminutes.com/docs/python/) <br><br> 
First, let's start with a simple command to print out "Hello, World!" using the `print()` function. Throughout this tutorial, we will use `print()` function to output results.

In [9]:
# this is a comment
print("Hello, World!") 

Hello, World!


Printing is simple in python and the output can be formatted as we like. We can format the output using `f` before the content we want to print as you will see in the following sections. <br><br> Another thing you will see throughout are comments. These are very helpful when it comes to documentation. Comments in python start with #.

Python will ignore string literals that are not assigned to a variable. Thus, you can add a block of comments in your code as follows:

In [10]:
"""
This is a block of 
comments written in 
more than one line
"""
print("Hello, World!")

Hello, World!


### Assigning values to variables and data types
The assignment operator is `=`. If `x = y`, then the value of `y` will be assigned to `x` and as a result, both `x` and `y` will carry the same value. 

In [5]:
a = 10
b = 5.5
c = 'whatever'
d = "dude" # notice that both single and double quotes create a string
e = '!' # python does not have a character-type. Even a single entity inside '' is a string

# printing the output
print(a, b)
print(f'a={a} and b={b}') # formatting the output using 'f' before the content we want to print
print() # prints a blank line
print("The variables are",a, b, c,'',d,e) # empty quotes add space in the output
print(type(a), type(b), type(c), type(d), type(e)) # prints the type of a variable

10 5.5
a=10 and b=5.5

The variables are 10 5.5 whatever  dude !
<class 'int'> <class 'float'> <class 'str'> <class 'str'> <class 'str'>


You don't need declare the type of your variable, you can even change its type later. An example:

In [2]:
x = 3       # x is of type int
x = "three" # x is now of type str
print(x, type(x))

y = '3'

three <class 'str'>


You can also specify the type of the variable through casting:

In [23]:
x = str(3)    # x will be '3'
y = int(3)    # y will be 3
z = float(3)  # z will be 3.0

print(f'x = {x} {type(x)}\ny = {y} {type(y)}\nz = {z} {type(z)}')

x = 3 <class 'str'>
y = 3 <class 'int'>
z = 3.0 <class 'float'>


You can assign values to multiple variables in one line:

In [27]:
x, y, z = 1, 2 ,3

print(x,y,z)

1 2 3


### Variable names

Variable names are case-sensitive in python:

In [24]:
x = 3
X = "three"
#X will not overwrite x

print(x, X)

3 three


A variable can have names as brief as `x` or `y`. It can also have a more descriptive name such as `name`, `fullname` or `full_name`. Here are rules for naming Python variables:
* Must start with a letter or the underscore character
* Cannot start with a number
* Can only contain alpha-numeric characters and underscores (A-z, 0-9, and _ )
* Cannot be any of Python's keywords (if, True, for, etc.).

### Mathematical operations
Python, by default, can do basic mathematical operations like addition, multiplication, etc. Here we present a few examples. Please visit [this](https://www.tutorialspoint.com/python/python_basic_operators.htm) document for further details and more examples.

In [7]:
print('The sum of a and b is ', a+b)
print('The sum of c and d is ',c+' '+d+e) # yes, strings can be added too
# print(a+c) would not work because one is 'int' and the other is 'string'

diff_ab = a-b # creating a new variable and assigning it a value
prod_ab = a*b

print(f'\na-b = {diff_ab}') # \n is to introduce a newline 
print(f'\na*b = {prod_ab}')
print(f'\nDivision can be done in two ways: a/b gives {a}/{b} =',a/b) # gives the exact answer
print('and a//b gives =',a//b) # integer division is done by '//'. It returns the smaller integer number
                                   # e.g. 5//2=2.0

The sum of a and b is  15.5
The sum of c and d is  whatever dude!

a-b = 4.5

a*b = 55.0

Division can be done in two ways: a/b gives 10/5.5 = 1.8181818181818181
and a//b gives = 1.0


Here is the list of mathematical operations:

* Addition: `+`
* Subtraction: `-`
* Multiplication: `*`
* Division: `/`
* Modulus: `%`
* Exponentiation: `**`
* Floor division: `//`

For more types of operators, [click here](https://www.geeksforgeeks.org/python-operators/#).

> One thing you will find useful is formating your printing to control how many digits you want displayed. The will come in handy when you are asked to what order your results are. Check the example below:

In [144]:
z = 154/251

print(z)
print(f'{z:.2f}')  ## 3 significant digits
print(f'{z:.2e}')  ## 3 significant digits in scientific notion

print(f'\n{5:.3f}')
print(f'{5:5e}')

0.6135458167330677
0.61
6.14e-01

5.000
5.000000e+00


### Lists
Lists are an important part of the python data-structures and are used to store multiple items in a single variable. Lists are dynamic, which means that their size can be changed and their elements can also be changed. There is a lot that can be done to and with a list. We recommend going through [this](https://docs.python.org/3/tutorial/datastructures.html) webpage to get familiar with the things that can be done to and with a list. Please also read about tuples and how they differ from lists. 

In [9]:
list1 = [1,3,5.6,'animal','234',2]
print(list1)

list2 = ['another',1,'coz','y not',23, 6.5]
print('\n',list2)

# lists can be added- the output is a concatenated list (not the sum of the elements)
long_list = list1+list2
print(long_list)

# the list size can be changed by appending or popping out elements
list1.append('this is a new element')
print('\n',list1)
list1.pop() # pop() removes the last element of the list
print(list1)

[1, 3, 5.6, 'animal', '234', 2]

 ['another', 1, 'coz', 'y not', 23, 6.5]
[1, 3, 5.6, 'animal', '234', 2, 'another', 1, 'coz', 'y not', 23, 6.5]

 [1, 3, 5.6, 'animal', '234', 2, 'this is a new element']
[1, 3, 5.6, 'animal', '234', 2]


One very important feature that you will find useful when dealing with lists, especially when looping over one, is to find its length (or how many elements it has) using the line:
```python
len(list1)
```

In [5]:
list1 = [0,1,2,3]
print('the length of the list:', len(list1))

the length of the list: 4


to access single elements of the list:

In [6]:
print(list1[2])

2


to create an empty list:

In [8]:
empty_list = []

print(empty_list, len(empty_list))

[] 0


for more functions applicable to lists, please visit the webpage linked above.

### Dictionary
Dictionary stores pairs of values (key and value). It is used to store data differently than lists and arrays. Just like lists, dictionaries can store keys and values of any type. We can also have nested dictionaries where keys can have dictionaries as values (an example provided below). For further reading, please visit [GeeksforGeeks](https://www.geeksforgeeks.org/python-dictionary/). 

In [10]:
# One easy way to create a dictionary
Dict = {1:'name','second element':'age',3:'gender'}

print(Dict)
print(Dict[1],Dict['second element']) # accessing the element value by key

# accessing elements in a loop
print('\nPrinting dictionary items in a for loop')
for item in Dict.items():
    print(item)
    
# accessing all keys and values at once
print('\nAccessing keys and values')
keys = Dict.keys()
values = Dict.values()
print(keys,values)
print()

# # Another easy way to create a dictionary (Nested dictionary, as an example)
Dict1 = {} # first, let's build an empty dictionary
Dict1['first element'] = 'name'
Dict1[2] = 'age'
Dict1['last element (a dictionary)'] = {1:'Ram',2:'Bharose'}
print(Dict1)

{1: 'name', 'second element': 'age', 3: 'gender'}
name age

Printing dictionary items in a for loop
(1, 'name')
('second element', 'age')
(3, 'gender')

Accessing keys and values
dict_keys([1, 'second element', 3]) dict_values(['name', 'age', 'gender'])

{'first element': 'name', 2: 'age', 'last element (a dictionary)': {1: 'Ram', 2: 'Bharose'}}


### Boolean operations
Boolean result can either be True or False. True and False have numeric values 1 and 0, respectively, i.e., True == 1 and False == 0. <br>
'and', 'or', 'not', and comparison operators (<, >, ==, !=, <=, >=) fall under boolean operators. 'not' operator requires only one argument and it simply negates the result. For instance, not Ture == False. 'and' and 'or' require two arguments. The output of 'and' is True if both arguments are true. The output of 'or' is True if one of the arguments is true. The comparison operators hold straightforward mathematical meaning. We present some examples to make it clear.

In [35]:
print(f'is 1 == 2? {1 == 2}')
print(f'is 1 != 2? {1 != 2}')
print(f'is 1 > 2? {1 > 2}')
print(f'is 1 >= 2? {1 >= 2}')
print(f'is 1 <= 2? {1 <= 2}')

print()
print(True or False)
print(True and False)
print(True and True)
print(False or False)

print()
print(1 <= 2 or 1 == 2) # first argument is True but the second is False
print(1 <= 2 and 1 >= 2) # first argument is True but the second is False

print()
print(True*1.0, True*1) # we can convert True and False to float and integer
print(False*1.0)

is 1 == 2? False
is 1 != 2? True
is 1 > 2? False
is 1 >= 2? False
is 1 <= 2? True

True
False
True
False

True
False

1.0 1
0.0


In [12]:
list_1 = [False, False, False]
list_2 = [True, True, True]

print(sum(list_1))
print(sum(list_2))

0
3


## Conditions and Loops
The simple examples below demonstrate how if-else conditions and loops (while and for) can be used. With each if-else condition, multiple conditions used. For instance, 'if condition1 or condition2 and condition3: '. In this example, if either of the first two conditions is true and the third one is also true, then the statements inside 'if' will be executed.

> One important characteristic of the Python language is indentation as it uses is to indicate a block of code, the case with if conditions, functions and for/while loops. The colon `:` is what indicates an upcoming block of code.

In [4]:
a = 10
b = 5.5

# first example
if a > b:
    print('a is greater than b')
else:
    print('nevermind!')

# second example
if a <= b or a == b:
    print('a is greater than b')
elif a != b and a < b:
    print('b is not equal to a')
else: 
    print('none!')
    
print()

# while loop
while b < a:
    b = b + 1
    print(b)

# same can be done using a 'for' loop but we will need to either specify the number of iterations 
# or use an 'if' condition
b = 5.5
print()
for i in range(5): # we should know the number of required iterations beforehand
    b = b + 1
    print(b)
    
b = 5.5
print()
for i in range(100): # we can provide a large enough number of iterations and use an 'if' condition
    if b < a:
        b = b + 1
        print(b)
        
b = 5.5
print()
for i in range(100): # we can provide an arbitarily large number of iterations and use an 'if-else' condition
    if b < a:
        b = b + 1
        print(b)
    else:
        break

# Note that the above two 'for' loops will run a different numbers of iterations. The loop with just the 'if' 
# condition will run 100 iterations, while the one with 'if-else' will break when b > a (after 5 iterations). 


a is greater than b
none!

6.5
7.5
8.5
9.5
10.5

6.5
7.5
8.5
9.5
10.5

6.5
7.5
8.5
9.5
10.5

6.5
7.5
8.5
9.5
10.5


***
<span style="color: blue"> <b>Exercise 1: Use a for loop to store all even numbers from 0 to 20 in a list. <br></b> 
    1) Start by creating an empty list. <br> 2) Run a for loop that goes from 0 to 20 (remember that `range(a,b)` does not include the endpoint `b`). <br> 3) Setup a condition to only append values whose division by 2 gives 0. <br> 4) Print the list when you are done </span> 

***

## Functions

### Homemade functions

Writing functions in python is simple! We use the keyword `def` before the function name and put `():` at the end. For example, `def func_name(parameters):`. The `parameters` in the function definition are called `arguments` when calling the function and passing the values for the parameters. Hopefully, it will be clear from the examples below. 
Inside a function, we can manipulate the values of the arguments, create new variables, run loops, etc. If we want an output from a function, we need to use `return variable_name1, variable_name2, ..., variable_nameN` at the end of the function. Thus, we can have as many output variables returned from the fucntions as we need and they can be of any datatype. We can also write functions without return, e.g., if we just want to print something. A few examples are provided below. 
<br>A lot of useful information on python fucntions is available on [Programiz](https://www.programiz.com/python-programming/function), [w3schools](https://www.w3schools.com/python/python_functions.asp), and [GeeksofGeeks](https://www.geeksforgeeks.org/python-functions/). All the three sources are great. Please follow the one you like better.
<br>We strongly suggest that you practice writing functions because it is something you will do all the time in computational physics course and also in your own research.

In [38]:
# First example with no parameters passed or values returned
def hello_function():
    print("Hello from a function!")
    
hello_function()

Hello from a function!


In [43]:
# Second example that takes a variable and returns it squared
def square(x):
    return x**2

y = square(2)
print(y)

4


In [44]:
## More examples ##

# a function that adds two lists and prints the output without a return value and parameters
def print_list():
    list1 = [1,3,5.6,'animal','234',2]
    list2 = ['another',1,'coz','y not',23, 6.5]
    long_list = list1+list2
    print('Lists provided: ',list1,' and ',list2)
    print('The combination of the two is ',long_list)
    
# note that defining a function does not execute it. To run it, we need to call it
print_list() # this is how we can make a funciton run by calling it

# we could define another function that does the exact same thing as above but takes one parameter (we can also 
# provide it two, if we like)
print()
def print_list_withArg(list_input):
    list2 = ['another',1,'coz','y not',23, 6.5]
    long_list = list_input+list2
    print('List provided: ',list_input,' and the list added is ',list2)
    print('The combination of the two is ',long_list)
    
# this time, we need to provide the argument to the function to run it (when we call it)
list1 = [1,3,5.6,'animal','234',2] # the list we will pass to the function
print_list_withArg(list1) # notice that the parameter name in the function definition has nothing to do with the 
                          # argument name initialized outside the function.
#   **** In the above example, 'list_input' is the function parameter, while 'list1' is the function argument ****

# we could define another function that does the exact same thing as above but takes two parameters and returns 
# three outputs
def print_list_withArg_output(list_input1, list2):
    long_list = list_input1+list2
    return long_list, list_input1, list2
    
list1 = [1,3,5.6,'animal','234',2]
list2 = ['another',1,'coz','y not',23, 6.5]
 
output1, output2, output3 = print_list_withArg_output(list1, list2) # this puts the output in separate variables
print('\nThe returned variables are in individual output variables',output1, output2, output3)
function_outputs = print_list_withArg_output(list1, list2) # this puts the three outputs in a tuple
print('\nThe returned variables are in a tuple',function_outputs)

Lists provided:  [1, 3, 5.6, 'animal', '234', 2]  and  ['another', 1, 'coz', 'y not', 23, 6.5]
The combination of the two is  [1, 3, 5.6, 'animal', '234', 2, 'another', 1, 'coz', 'y not', 23, 6.5]

List provided:  [1, 3, 5.6, 'animal', '234', 2]  and the list added is  ['another', 1, 'coz', 'y not', 23, 6.5]
The combination of the two is  [1, 3, 5.6, 'animal', '234', 2, 'another', 1, 'coz', 'y not', 23, 6.5]

The returned variables are in individual output variables [1, 3, 5.6, 'animal', '234', 2, 'another', 1, 'coz', 'y not', 23, 6.5] [1, 3, 5.6, 'animal', '234', 2] ['another', 1, 'coz', 'y not', 23, 6.5]

The returned variables are in a tuple ([1, 3, 5.6, 'animal', '234', 2, 'another', 1, 'coz', 'y not', 23, 6.5], [1, 3, 5.6, 'animal', '234', 2], ['another', 1, 'coz', 'y not', 23, 6.5])


### Built-in Functions

There are many built-in functions you can use directly. For the full list, [click here](https://www.w3schools.com/python/python_ref_functions.asp).

Here are a few examples:

In [48]:
x = -3
y = 4
z = 1

# function to return the absolute value of a variable
print(abs(x))

a_list = [x,y,z]

# function to return the sum of items in a list
print(sum(a_list))

# Two functions to return the min and max of a list
print(min(a_list), max(a_list))

3
2
-3 4


***
<span style="color: blue"> <b>Exercise 2: Write your own function that takes a list and returns the sum of its elements, then compare what you get with the built-in `sum()` function. </b> </span> 

***

## Python Modules

You can consider a module to be a file containing a set of functions you can import and use in your code. You can either write your own module, or use one of the many modules available out there. When it comes to Python, there are many great modules that can be used and are actually the reason the Python language is most popular. Modules made calculations such as solving DEs, solving integrals, Fourier transforms, and more that you will learn about in your Computational Physics class as simple as a one line code.

In this tutorial, we will go over the most popular modules that will often use in your python programming and will most definitely need in your upcoming computational course or in your research.

## NumPy

Numpy stands for numerical python. It provides most of the functionalities required for numerical or statistical computing. Our numerical methods / computational physics course will require us to use this library all the time. There is extensive documentation on NumPy data-structures and functions functions. For more on why we need NumPy, please visit this [webpage](https://numpy.org/doc/stable/user/whatisnumpy.html). The basics of NumPy can be found [here](https://numpy.org/doc/stable/user/absolute_beginners.html) and [there](https://numpy.org/doc/stable/user/quickstart.html).

We will go over how to load it in our codes and how to call functions and learn about some array and matrix operations needed for the computational physics course. 

We suggest going through [NumPy fundamentals](https://numpy.org/doc/stable/user/basics.html) online for an extensive documentation. It is not possible to remember all the data types, structures, or functions that NumPy offers. Therefore, one has to refer to NumPy's official documentation or look for answers on google. Both are great! You may use this link for quick [reference](https://numpy.org/doc/stable/reference/index.html#reference). There are many more sources to learn NumPy- they all introduce NumPy functions, etc. in their own style- one may work better than the other for you, e.g., [GeeksforGeeks](https://www.geeksforgeeks.org/python-numpy/) and 
[w3schools](https://www.w3schools.com/python/numpy/numpy_intro.asp). 

> You need to make sure that NumPy is installed on your local machine to be able to use it. [Click here](https://numpy.org/install/) to look into how to do so.


### Importing NumPy and generating NumPy arrays
NumPy arrays are fixed in size. It means that if an array is initialized with N elements, its size and shape can not be changed, while the values of the elements can be changed. We can have 1D, 2D, and higher dimensional arrays but we will stick to 1D and 2D in this tutorial.

For any module, we need to first include/import the library in python. We can do that by using `import`. To give it a 
shorter name, we can use `as`. The most common short-name used for NumPy is `np` and so the line for importing the module will be:
```python
    import numpy as np
```
now one can call any NumPy function using `np.func_name(parameters)`. Let's now look into how to create a NumPy array. You can do so using the line:
```python
    array1 = np.array([1,2,3,4])
```
This gets you a 1D array with 4 elements. You can use `np.shape(array1)` to check the dimensions of any array you have.

In [28]:
import numpy as np

# You can create a numpy array as follows:
array1 = np.array([1,2,7,5])
print(array1)
print(type(array1)) # all numpy arrays are of type ndarray (n-dimensional array)
print(np.shape(array1))

[1 2 7 5]
<class 'numpy.ndarray'>
(4,)


You can also convert a list to a numpy array as follows:

In [62]:
# creating a numpy array from a list (all elements of the list must be numeric)
list1 = [8,7,2,1]
array2 = np.array(list1)
print(array2)
print(type(array2)) # all numpy arrays are of type ndarray (n-dimensional array)

[8 7 2 1]
<class 'numpy.ndarray'>


You can create a 2D array, you have to enclose it with two brackets:

In [68]:
# You can create a 2D numpy array as follows:
array3 = np.array(([1,2,7,5], [8,7,2,1]))
print(array3)
print(type(array3)) # all numpy arrays are of type ndarray (n-dimensional array)
print('The shape of the array is ', np.shape(array3))

# using two lists (lists must be of same size, i.e., same number of elements)
print('\n------------------------------------')
list1 = [1,2.7,3]
list2 = [4.0,5,6]
array2d = np.array([list1,list2])
print('The shape of the 2D array is ', array2d.shape)
print(array2d)

[[1 2 7 5]
 [8 7 2 1]]
<class 'numpy.ndarray'>
The shape of the array is  (2, 4)

------------------------------------
The shape of the 2D array is  (2, 3)
[[1.  2.7 3. ]
 [4.  5.  6. ]]


Two very useful functions are the `np.arange()` and `np.linspace()` to generate arrays of desired spacing and size, respectively. These are especially useful when making plots.


In [77]:
array4 = np.arange(1,10,0.5) # this will create an array of elements from 1 to 10 with a spacing of 0.5 (10 excluded)
array5 = np.linspace(1,10,20) # this will create an array with 20 elements from 1 to 10 with equal spacing

print('Array with np.arange():\n',array4)
print('\n------------------------------------')
print('\nArray with np.linspace():\n',array5)

Array with np.arange():
 [1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]

------------------------------------

Array with np.linspace():
 [ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


### Numpy array slicing
We often only need a part of the array for the calculations. You can access specific elements or sections of the arrays by 'slicing' an array using 'array[m:n]'. The slice then picks up elements from index m to n-1.
>We should remember that the element indexing in python begins at 0. This means that the first element of an array is at index 0. 

In [99]:
arr = np.arange(0,9) # when spacing is not specified, numpy assumes it to be 1
arr_slice = arr[3:8] # picking up element at index 3 to the one at 7 in the slice
element1 = arr[5] # putting the 6th element of the array in element1
arr_slice2 = arr[5:] # picking up element at index 5 to the end


print('original array:', arr)
print('fourth to eighth elements of the array:', arr_slice)
print('sixth element:', element1)
print('sixth element to the end of the array:', arr_slice2)


original array: [0 1 2 3 4 5 6 7 8]
fourth to eighth elements of the array: [3 4 5 6 7]
sixth element: 5
sixth element to the end of the array: [5 6 7 8]


If you need to access the array in reverse, you can use negative indices. Here is an example: 

In [106]:
arr = np.arange(0,9)
element1 = arr[-1] # the last element of the array
arr_slice = arr[-3:] # picking up element at index [len(arr)-3] to the end

print('original array:', arr)
print('length of array:', len(arr))
print('last element of the array:', element1)
print('arr[len(arr)-3]:', len(arr)-3)
print('from [len(arr)-3] to the end:', arr_slice)


original array: [0 1 2 3 4 5 6 7 8]
length of array: 9
last element of the array: 8
arr[len(arr)-3]: 6
from [len(arr)-3] to the end: [6 7 8]


In [107]:
# to access elements of 2D arrays, we need to provide to indices array[row_index,column_index]
arr2d = np.arange(1,9).reshape(2,4) # .reshape(m,n) converts a 1D array to a 2D array with m rows and n columns
print('------------------------------------')
print(arr2d)
print(arr2d[1,3]) # prints the element in 2nd row (row index 1) and 4th column (column index 3)

# we can also access specific rows or columns
row = arr2d[1,:] # picks up all columns of 2nd row
col = arr2d[:,2] # picks up all rows of 3rd column
print('------------------------------------')
print('2nd row of arr2d = ',row)
print('3rd col of arr2d = ',col)

------------------------------------
[[1 2 3 4]
 [5 6 7 8]]
8
------------------------------------
2nd row of arr2d =  [5 6 7 8]
3rd col of arr2d =  [3 7]


### NumPy operations
if a scalar is added to, subtracted from, multiplied by, or divided by an array, then all elements of the array undergo that operation. One can call it element-wise operation. If two arrays of equal size are added to, subtracted from, multiplied by, or divided by each other, element-wise operation occurs. Raising an array to a power also performs element-wise operation by raising every element to that power. It works for multi-dimensional arrays as well. Some examples below will make it easier to understand. 

In [108]:
arr = np.arange(0,9)
a = 10

# arrays with scalars
print('Original array = ',arr)
print('a scalar (=10) added to the original array (arr+a) = ',arr+a)
print('a scalar subtracted from the original array (arr-a) = ',arr-a)
print('Original array divided by a scalar (arr/a) = ',arr/a)
print('Original array multiplied by a scalar (arr*a) = ',arr*a)
print('Original array raised to power 4 (arr**4) = ',arr**4)
print('\n------------------------------------\n')

# arrays with arrays
arr2 = np.arange(1,10) 
print(f'Original arrays = {arr} and {arr2}')
print('sum of the two arrays (arr+arr2) = ',arr+arr2)
print('subtracting the second array from the first (arr-arr2) = ',arr-arr2)
print('dividinjg the first array by the second (arr/arr2) = ',arr/arr2)
print('product of the two arrays (arr*arr2) = ',arr*arr2)
print('First array raised to the second (arr**arr2) = ',arr**arr2)
print('\n------------------------------------\n')

Original array =  [0 1 2 3 4 5 6 7 8]
a scalar (=10) added to the original array (arr+a) =  [10 11 12 13 14 15 16 17 18]
a scalar subtracted from the original array (arr-a) =  [-10  -9  -8  -7  -6  -5  -4  -3  -2]
Original array divided by a scalar (arr/a) =  [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8]
Original array multiplied by a scalar (arr*a) =  [ 0 10 20 30 40 50 60 70 80]
Original array raised to power 4 (arr**4) =  [   0    1   16   81  256  625 1296 2401 4096]

------------------------------------

Original arrays = [0 1 2 3 4 5 6 7 8] and [1 2 3 4 5 6 7 8 9]
sum of the two arrays (arr+arr2) =  [ 1  3  5  7  9 11 13 15 17]
subtracting the second array from the first (arr-arr2) =  [-1 -1 -1 -1 -1 -1 -1 -1 -1]
dividinjg the first array by the second (arr/arr2) =  [0.         0.5        0.66666667 0.75       0.8        0.83333333
 0.85714286 0.875      0.88888889]
product of the two arrays (arr*arr2) =  [ 0  2  6 12 20 30 42 56 72]
First array raised to the second (arr**arr2) =  [     

### Loading and saving data files with numpy
A variety of file formats can be read and saved by numpy. We will go through two of the numpy functions that allow us to do that- [np.loadtxt()](https://numpy.org/doc/stable/reference/generated/numpy.loadtxt.html) and [np.savetxt()](https://numpy.org/doc/stable/reference/generated/numpy.savetxt.html). Clicking on these links will take you the documentation of the two functions. 
<br> If a data file exists in th edirectory that your current code is in, we can simply type the filename in np.loadtxt(filename). If the file is in some other directory, we need to specify the path along with the filename. np.savetxt() requires a filename (if the file does not already exist, the function automatically generates it) in which the data needs to be saved, the data itself, and formatting, if any. The example below demonstrates how to use these two functions. There is a lot more that numpy offers related to files. Please take help of the internet, there are many good sources to learn from. 

In [13]:
import numpy as np

X = np.random.uniform(-10,10,size=[20,5]) # the data that we would like to save in a file

np.savetxt('NewFIle.dat',X,fmt='%.3f    %.3f    %d    %d    %d') # this way we can store the X data in 
                                                                 # the NewFile with specified format-
                                                                 # first two columns upto 3 decimal places
                                                                 # and the last three columns as integers

data = np.loadtxt('NewFIle.dat') #  puts the data from the file into the variable 'data'
data # prints the loaded data

array([[-6.18 ,  2.233, -7.   ,  6.   ,  5.   ],
       [-4.558,  1.657,  8.   ,  1.   ,  5.   ],
       [ 9.48 ,  2.075, -5.   , -1.   , -6.   ],
       [-1.373,  1.16 ,  7.   , -6.   ,  5.   ],
       [-3.874, -6.319,  2.   ,  6.   , -8.   ],
       [-6.768, -8.058,  4.   ,  0.   , -7.   ],
       [-2.208, -8.935,  0.   , -1.   ,  0.   ],
       [-5.094, -7.5  , -7.   , -4.   ,  0.   ],
       [-2.429,  4.053, -3.   ,  6.   , -2.   ],
       [ 1.325,  9.471,  2.   , -2.   , -1.   ],
       [ 3.474, -9.67 ,  0.   , -5.   ,  6.   ],
       [-2.048, -5.987,  9.   ,  2.   ,  8.   ],
       [ 1.693, -0.249,  3.   , -9.   ,  2.   ],
       [ 4.776,  4.797, -2.   ,  0.   ,  2.   ],
       [-8.599,  6.102, -8.   ,  3.   ,  0.   ],
       [ 6.415,  8.019, -1.   , -3.   ,  7.   ],
       [ 9.603,  0.878,  0.   , -8.   ,  3.   ],
       [-1.281, -7.862,  0.   ,  0.   ,  0.   ],
       [ 8.476,  9.369,  6.   ,  7.   ,  6.   ],
       [ 1.555,  0.093,  2.   ,  6.   , -7.   ]])

### Linear algebra using numpy
Numpy includes funcitons that can applied to arrays to obtain the determinant, eigenvalues, eigenvectors, inverse, products, and solve equations. We simply need to import linalg package in numpy to use the functions.

In [38]:
import numpy as np
from numpy import linalg as lg

A = np.arange(1,10).reshape(3,3)
determinant = lg.det(A)
A_inv = lg.inv(A) # inverse of A

print("The matrix is ",A)
print("\nDeterminnat of A is ",determinant)
print("\nInverse of A is ",A_inv)

# Eigenvalues and eigenvectors can be calculated together using eig()
eigvals, eigvecs = lg.eig(A)
print("\nEigenvalues of A are: ",eigvals)
print("\nEigenvectors of A are: ",eigvecs)

# Solving a set of linear equations AX=B, A- 2D array, X and B- 1D arrays
# Eq.1: 2x1 + 5x2 = 8
# Eq.2: 3x1 - 9x2 = 0
# solve for x1 and x2
A = np.array([[2,5],[3,-9]])
B = np.array([8,0])
x1,x2 = lg.solve(A,B)
print("\nSolution for the equations (values of x1 and x2) '2x1 + 5x2 = 8' and '3x1 - 9x2 = 0' are ",x1,x2)

The matrix is  [[1 2 3]
 [4 5 6]
 [7 8 9]]

Determinnat of A is  6.66133814775094e-16

Inverse of A is  [[-4.50359963e+15  9.00719925e+15 -4.50359963e+15]
 [ 9.00719925e+15 -1.80143985e+16  9.00719925e+15]
 [-4.50359963e+15  9.00719925e+15 -4.50359963e+15]]

Eigenvalues of A are:  [ 1.61168440e+01 -1.11684397e+00 -4.22209278e-16]

Eigenvectors of A are:  [[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]

Solution for the equations (values of x1 and x2) '2x1 + 5x2 = 8' and '3x1 - 9x2 = 0' are  2.181818181818182 0.7272727272727273


### Other NumPy functions
There is a huge set of functions available in NumPy- almost everything we will need for numerical computing. The aim is to give you a hands on expeience with NumPy so that you become comfortable using it anytime you need it.

All the functions can be called by their names and using `np.` before them if you imported NumPy as np. It is advisable to always google the function name and examples whenever you have to use one. It allows you to know what parameters a given function takes and what outputs it generates. 

Here are a few useful examples for NumPy functions:

In [125]:
arr = np.array([3,2,2,1,2,-4])

print(f'Original array: {arr}') 
print(f'The mean = {np.mean(arr)}')
print(f'The standard deviation = {np.std(arr)}') 
print(f'The index of largest element = {np.argmax(arr)}, which is {np.max(arr)}')
print(f'The index of smallest element = {np.argmin(arr)}, which is {np.min(arr)}')
print(f'Sorted array: {np.sort(arr)}') # sorts array in ascending order
print(f'The indices where the array is equal to 2: {np.where(arr==2)[0]}')
print(f'Absolute values: {np.abs(arr)}')
print(f'Sum of array: {np.sum(arr)}')
print(f'Sum of the absolute values of the array: {np.sum(np.abs(arr))}')

Original array: [ 3  2  2  1  2 -4]
The mean = 1.0
The standard deviation = 2.309401076758503
The index of largest element = 0, which is 3
The index of smallest element = 5, which is -4
Sorted array: [-4  1  2  2  2  3]
The indices where the array is equal to 2: [1 2 4]
Absolute values: [3 2 2 1 2 4]
Sum of array: 6
Sum of the absolute values of the array: 14


***
<span style="color: blue"> <b>Exercise 3: Create a numpy array with only even numbers from 0 to 10 (including 10) using `np.arange()`. Then, with a for loop, calculate the mean of your array. Compare your answer with the result of `np.mean()`. </b> <br><br> Hint: You can refer to the previous exercise for calculating the sum of a list along with len(array) to finish calculating the average of your array. </span> 

***

## Other Modules
There are many other modules that can be used in Python. We'll briefly go over two of them, but feel free to google for more.


### SciPy

SciPy is another library often used for scientific computing. It is built on NumPy and extends it to more functions and better accuracy in some cases. SciPy [user guide](https://docs.scipy.org/doc/scipy/tutorial/index.html#user-guide) provides a list of sub-packages. Some of the sub-packages useful for us are `linalg`, `stats`, `special`, `fftpack`, `integrate`, and `interpolate`. Please go over to the user guide and get acquainted with these functions. We can import any package (library) just as we did NumPy. 


### Pandas
Pandas is used mainly for data manipulation, analysis, and visualilzation. It is far more powerful and convinient than microsoft excel for similar tasks. It can load data files of almost all formats and generate a series or a dataframe. A <b> dataframe</b> is simply a representation of tabular data. It is 2D (has rows and columns) and all elements, including complete rows and columns can be manipulated, e.g., deleted, added, imputed, visualized, extracted, etc. A great source of information on pandas and its capabilities are given on its official [website](https://pandas.pydata.org/docs/user_guide/index.html). 

An example of how data is represented in a Pandas dataframe is given below:

In [118]:
import pandas as pd

data = {
    "Name": ["Alice", "Bob", "Charlie", "Diana", "Ethan", "Fay", "George", "Hannah", "Ian", "Julia"],
    
    "Age": [25, 30, 35, 28, 22, 40, 29, 31, 24, 27],
    
    "Department": ["Physics", "Math", "Biology", "Chemistry", "Math", "Physics", "Biology", "Chemistry", "Physics", "Math"],
    
    "Score": [88.5, 92.0, 79.5, 85.0, 91.2, 76.5, 89.0, 84.3, 95.0, 87.6],
    
    "Passed": [True, True, False, True, True, False, True, True, True, True],
    
    "Join_Year": [2022, 2021, 2020, 2023, 2022, 2020, 2021, 2022, 2023, 2021]
}

print(type(data))
df = pd.DataFrame(data)
print(type(df))
df

<class 'dict'>
<class 'pandas.core.frame.DataFrame'>


Name  Age Department  Score  Passed  Join_Year
0    Alice   25    Physics   88.5    True       2022
1      Bob   30       Math   92.0    True       2021
2  Charlie   35    Biology   79.5   False       2020
3    Diana   28  Chemistry   85.0    True       2023
4    Ethan   22       Math   91.2    True       2022
5      Fay   40    Physics   76.5   False       2020
6   George   29    Biology   89.0    True       2021
7   Hannah   31  Chemistry   84.3    True       2022
8      Ian   24    Physics   95.0    True       2023
9    Julia   27       Math   87.6    True       2021

We can also generate a dataframe from a numpy array

In [50]:
X = np.arange(1,16).reshape(5,3)
frame = pd.DataFrame(X)
frame

0   1   2
0   1   2   3
1   4   5   6
2   7   8   9
3  10  11  12
4  13  14  15

#### Series
A Pandas Series is a one-dimensional labeled array storing data of any type (integers, strings, floats, Python objects, etc.).

In [119]:
series = df["Name"]  # Access a Series in a defined dataframe
series

0      Alice
1        Bob
2    Charlie
3      Diana
4      Ethan
5        Fay
6     George
7     Hannah
8        Ian
9      Julia
Name: Name, dtype: object

In [120]:
## You can also construct a Series from a dictionary with an Index specified
d = {'a': 1, 'b': 2, 'c': 3}
ser = pd.Series(data=d, index=['a', 'c'])
ser

a    1
c    3
dtype: int64

#### Columns
Each column in a Pandas Dataframe is essentially a Series, meaning it holds one type of data (int, float, str, etc.) and has an index aligned with the rows.

In [121]:
## Accessing a single column
column = df["Name"]                 # Returns a Series
print(column,type(column))
column = df[["Name", "Age"]]        # Returns a DataFrame with multiple columns
print(column,type(column))

0      Alice
1        Bob
2    Charlie
3      Diana
4      Ethan
5        Fay
6     George
7     Hannah
8        Ian
9      Julia
Name: Name, dtype: object <class 'pandas.core.series.Series'>
      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35
3    Diana   28
4    Ethan   22
5      Fay   40
6   George   29
7   Hannah   31
8      Ian   24
9    Julia   27 <class 'pandas.core.frame.DataFrame'>


In [122]:
all_columns = df.columns        # Returns an Index object of column names
all_columns_list = list(all_columns)     # Converts it to a list
print(all_columns_list)

['Name', 'Age', 'Department', 'Score', 'Passed', 'Join_Year']


In [123]:
# Renaming columns
df.rename(columns={"Name": "First_Name"}, inplace=True)

# Adding New Columns (as well as perform operations)
df["Expected_Graduation"] = df["Join_Year"] + 5
df

First_Name  Age Department  Score  Passed  Join_Year  Expected_Graduation
0      Alice   25    Physics   88.5    True       2022                 2027
1        Bob   30       Math   92.0    True       2021                 2026
2    Charlie   35    Biology   79.5   False       2020                 2025
3      Diana   28  Chemistry   85.0    True       2023                 2028
4      Ethan   22       Math   91.2    True       2022                 2027
5        Fay   40    Physics   76.5   False       2020                 2025
6     George   29    Biology   89.0    True       2021                 2026
7     Hannah   31  Chemistry   84.3    True       2022                 2027
8        Ian   24    Physics   95.0    True       2023                 2028
9      Julia   27       Math   87.6    True       2021                 2026

In [124]:
## You can also drop columns
df.drop(columns=["Age","Passed"], inplace=False) # when `inplace` is True, changes are made to the original Dataframe

First_Name Department  Score  Join_Year  Expected_Graduation
0      Alice    Physics   88.5       2022                 2027
1        Bob       Math   92.0       2021                 2026
2    Charlie    Biology   79.5       2020                 2025
3      Diana  Chemistry   85.0       2023                 2028
4      Ethan       Math   91.2       2022                 2027
5        Fay    Physics   76.5       2020                 2025
6     George    Biology   89.0       2021                 2026
7     Hannah  Chemistry   84.3       2022                 2027
8        Ian    Physics   95.0       2023                 2028
9      Julia       Math   87.6       2021                 2026

In [125]:
## You can also reorder columns
df = df[["First_Name", "Age", "Department" , "Score", "Join_Year", "Passed" , "Expected_Graduation"]]
df

First_Name  Age Department  Score  Join_Year  Passed  Expected_Graduation
0      Alice   25    Physics   88.5       2022    True                 2027
1        Bob   30       Math   92.0       2021    True                 2026
2    Charlie   35    Biology   79.5       2020   False                 2025
3      Diana   28  Chemistry   85.0       2023    True                 2028
4      Ethan   22       Math   91.2       2022    True                 2027
5        Fay   40    Physics   76.5       2020   False                 2025
6     George   29    Biology   89.0       2021    True                 2026
7     Hannah   31  Chemistry   84.3       2022    True                 2027
8        Ian   24    Physics   95.0       2023    True                 2028
9      Julia   27       Math   87.6       2021    True                 2026

#### Slicing
Slicing in pandas means selecting a subset of rows and/or columns from a DataFrame or Series. You can slice by:

* Row labels (`.loc`)

* Row positions (`.iloc`)

* Direct Python slicing (on Series or rows)

In [126]:
df.loc[2:5]           # Includes rows with labels 2, 3, 4, 5 (inclusive)

First_Name  Age Department  Score  Join_Year  Passed  Expected_Graduation
2    Charlie   35    Biology   79.5       2020   False                 2025
3      Diana   28  Chemistry   85.0       2023    True                 2028
4      Ethan   22       Math   91.2       2022    True                 2027
5        Fay   40    Physics   76.5       2020   False                 2025

In [127]:
df.loc[0:3, "First_Name":"Score"]   # Rows 0 to 3, columns from First_Name to Score

First_Name  Age Department  Score
0      Alice   25    Physics   88.5
1        Bob   30       Math   92.0
2    Charlie   35    Biology   79.5
3      Diana   28  Chemistry   85.0

In [128]:
df.iloc[0:3]          # Rows at positions 0, 1, 2 (stop is exclusive)

First_Name  Age Department  Score  Join_Year  Passed  Expected_Graduation
0      Alice   25    Physics   88.5       2022    True                 2027
1        Bob   30       Math   92.0       2021    True                 2026
2    Charlie   35    Biology   79.5       2020   False                 2025

In [129]:
df.iloc[2:5, 0:3]     # Rows 2–4, columns 0–2

First_Name  Age Department
2    Charlie   35    Biology
3      Diana   28  Chemistry
4      Ethan   22       Math

In [130]:
slice = df["Age"]
slice[2:5]               # Slice rows 2–4 of the "Age" Series

2    35
3    28
4    22
Name: Age, dtype: int64

In [131]:
## Column Slicing
df[["First_Name", "Score", "Department"]]  # Select specific columns

First_Name  Score Department
0      Alice   88.5    Physics
1        Bob   92.0       Math
2    Charlie   79.5    Biology
3      Diana   85.0  Chemistry
4      Ethan   91.2       Math
5        Fay   76.5    Physics
6     George   89.0    Biology
7     Hannah   84.3  Chemistry
8        Ian   95.0    Physics
9      Julia   87.6       Math

#### Filtering

In [132]:
scores_df = df[df["Score"] > 85].copy()           # Only rows where score > 85
scores_df

First_Name  Age Department  Score  Join_Year  Passed  Expected_Graduation
0      Alice   25    Physics   88.5       2022    True                 2027
1        Bob   30       Math   92.0       2021    True                 2026
4      Ethan   22       Math   91.2       2022    True                 2027
6     George   29    Biology   89.0       2021    True                 2026
8        Ian   24    Physics   95.0       2023    True                 2028
9      Julia   27       Math   87.6       2021    True                 2026

In [133]:
depart_df = df[df["Department"] == "Physics"].copy() # Only rows from the Physics department
depart_df

First_Name  Age Department  Score  Join_Year  Passed  Expected_Graduation
0      Alice   25    Physics   88.5       2022    True                 2027
5        Fay   40    Physics   76.5       2020   False                 2025
8        Ian   24    Physics   95.0       2023    True                 2028

In [134]:
pass_df = df[(df["Department"] == "Physics") & (df["Score"] > 85)].reset_index().copy() # Joining conditions
pass_df

index First_Name  Age Department  Score  Join_Year  Passed  \
0      0      Alice   25    Physics   88.5       2022    True   
1      8        Ian   24    Physics   95.0       2023    True   

   Expected_Graduation  
0                 2027  
1                 2028

#### Sampling
Sampling means randomly selecting rows (or columns) using the `.sample()` method.

In [110]:
#df.sample(n=3)            # Randomly select 3 rows
#df.sample(frac=0.1)       # Randomly select 10% of the rows
df.sample(n=2, axis=1)     # 2 random columns

Age  Join_Year
0   25       2022
1   30       2021
2   35       2020
3   28       2023
4   22       2022
5   40       2020
6   29       2021
7   31       2022
8   24       2023
9   27       2021

Follow [this link](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.sample.html) for the full documentation on `.sample()`.

#### Exporting/Importing Dataframes
Pandas also allows reading from and writing to various file formats like csv, json, excel, etc. Please visit [RealPython](https://realpython.com/pandas-read-write-files/#using-the-pandas-read_csv-and-to_csv-functions) for concise description for all formats.


In [138]:
# Exporting
df.to_csv("students.csv", index=False)

# Importing
df_csv = pd.read_csv("students.csv")
df_csv

First_Name  Age Department  Score  Join_Year  Passed  Expected_Graduation
0      Alice   25    Physics   88.5       2022    True                 2027
1        Bob   30       Math   92.0       2021    True                 2026
2    Charlie   35    Biology   79.5       2020   False                 2025
3      Diana   28  Chemistry   85.0       2023    True                 2028
4      Ethan   22       Math   91.2       2022    True                 2027
5        Fay   40    Physics   76.5       2020   False                 2025
6     George   29    Biology   89.0       2021    True                 2026
7     Hannah   31  Chemistry   84.3       2022    True                 2027
8        Ian   24    Physics   95.0       2023    True                 2028
9      Julia   27       Math   87.6       2021    True                 2026

## Concluding Remarks

Congratulations! You have completed the basic Python tutorial. There are tons of tutorials and resources out there you can use to learn more about Python or the modules most commonly used when coding in Python. You will learn with more practice, however, as there will be specific questions you will look for. Try solving the following problems in your own time:

1. Create a list of elements of your choice (different data-types) and print the elements one by one if the datatype is 'str' using first a for loop and then a while loop. <br><br>

2. Create two lists (list1 and list2) of numbers- one from 1 to 10 with a spacing of 1 and the other from 2 to 20 with a spacing of 2. Obtain the element-wise sum of list1 and list2, i.e., list1[0]+list2[0], and so on if the i-th element of the list1 is greater than 5. Otherwise, calculate the element wise difference, i.e., list1[0]-list2[0]. <br><br>

3. (Optional) Write a function that takes two parameters, prints them, and returns their sum, difference, product, and whether the numbers are prime or not. Test it by calling it with parameters 23 and 1000. Print your answers (returned variables) outside the function. <br><br>

4. Find the functions that allow you to insert, delete, and remove the elements from an array. Also find the functions that can be used to directly and indirectly sort arrays (the two are different!). Please familiarize yourselves with what parameters the functions need. <br><br>

5. Go to [GeeksforGeeks](https://www.geeksforgeeks.org/python-numpy/) or 
[w3schools](https://www.w3schools.com/python/numpy/numpy_intro.asp) to learn how to generate 1D and 2D arrays of random numbers with uniform, exponential, and normal distribution. Generate three arrays of 1000 elements, one for each distribution, and calculate their mean and variance. <br><br>

6. Search for functions that perform dot and cross products. Also look for functions that perform matrix multiplication. For two 2D arrays, do the functions for dot product and the matrix multiplication give the same result? Is there any difference between the two? <br><br>

7. (Optional) Write a function that takes two paramters, generates a matrix (or a 2D array) of size 10 by 10, with elements from a normal distribution with mean = parameter1 and standard deviation = parameter2. Change the elements of the array by multiplying the array by 100 and rounding the elements to the lower integer. Generate a second 10 by 10 array of ones and chnage its elements to 0 if the corresponding elements in the first array are below its mean value. Print both arrays and perform a matrix multiplication of the two. Also calculate the mean and standard deviation of the resultant matrix. Return the results.


***